@extends('layouts.app')
@section('title','Mon espace candidat — OROGNA Consulting')
@section('content')
<section class="bg-[#f5f7f3] py-14 lg:py-20"><div class="container-pro">
 <div class="grid gap-8 lg:grid-cols-[1.25fr_.75fr] lg:items-end">
  <div><span class="eyebrow">Espace candidat</span><h1 class="font-display mt-5 max-w-4xl text-4xl font-extrabold sm:text-6xl">Bonjour {{ auth()->user()->name }}.<br><span class="text-green-700">Votre carrière, votre espace.</span></h1><p class="mt-5 max-w-2xl text-lg leading-8 text-slate-600">Suivez vos candidatures, échangez directement avec l’équipe OROGNA et gardez toutes vos démarches au même endroit.</p></div>
  <div class="rounded-[28px] bg-[#123a2a] p-7 text-white shadow-xl"><div class="text-xs font-black uppercase tracking-[.18em] text-orange-300">Besoin d’aide ?</div><p class="mt-3 text-lg font-bold">Un recruteur peut vous répondre ici.</p><p class="mt-2 text-sm leading-6 text-white/65">Posez votre question sur une candidature, une offre ou votre dossier.</p></div>
 </div>
 <div class="mt-10 grid gap-4 sm:grid-cols-3"><div class="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100"><div class="text-xs font-black uppercase tracking-widest text-slate-400">Candidatures</div><div class="mt-2 text-4xl font-extrabold text-[#123a2a]">{{ $applications->count() }}</div></div><div class="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100"><div class="text-xs font-black uppercase tracking-widest text-slate-400">Messages</div><div class="mt-2 text-4xl font-extrabold text-orange-500">{{ $messages->count() }}</div></div><div class="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100"><div class="text-xs font-black uppercase tracking-widest text-slate-400">Compte</div><div class="mt-2 text-lg font-extrabold text-green-700">Actif</div></div></div>
 </div></section>
<section class="bg-white py-14"><div class="container-pro grid gap-8 lg:grid-cols-[1.1fr_.9fr]">
 <div class="rounded-[30px] border border-slate-200 bg-white p-7 shadow-sm sm:p-9"><div class="flex items-end justify-between gap-4"><div><span class="eyebrow">Suivi</span><h2 class="font-display mt-3 text-3xl font-extrabold">Mes candidatures</h2></div><a class="text-sm font-extrabold text-green-700" href="{{ route('jobs') }}">Voir les offres →</a></div><div class="mt-7 space-y-3">@forelse($applications as $application)<div class="rounded-2xl bg-slate-50 p-5"><div class="flex flex-col justify-between gap-3 sm:flex-row"><div><div class="font-extrabold">{{ $application->jobOffer?->title ?? 'Candidature spontanée' }}</div><div class="mt-1 text-sm text-slate-500">{{ $application->submitted_at?->format('d/m/Y à H:i') }}</div></div><span class="rounded-full bg-white px-3 py-1 text-xs font-black uppercase text-green-700 ring-1 ring-slate-200">{{ str_replace('_',' ', $application->status) }}</span></div></div>@empty<div class="rounded-2xl bg-slate-50 p-7 text-center text-sm text-slate-500">Aucune candidature pour le moment.<div class="mt-4"><a class="btn-primary" href="{{ route('apply') }}">Déposer mon CV ↗</a></div></div>@endforelse</div></div>
 <div class="rounded-[30px] bg-[#123a2a] p-7 text-white shadow-xl sm:p-9"><span class="eyebrow !text-orange-300">Messagerie</span><h2 class="font-display mt-3 text-3xl font-extrabold">Parler à OROGNA</h2><p class="mt-3 text-sm leading-6 text-white/65">Écrivez directement à notre équipe. Les réponses apparaîtront dans votre espace.</p><form method="POST" action="{{ route('candidate.messages.store') }}" class="mt-7">@csrf<textarea name="body" rows="7" required class="w-full rounded-2xl border border-white/10 bg-white/10 p-4 text-sm text-white outline-none placeholder:text-white/35 focus:border-orange-300" placeholder="Votre message..."></textarea><button class="mt-4 w-full rounded-full bg-orange-500 px-5 py-3.5 text-sm font-black text-white hover:bg-orange-600">Envoyer le message ↗</button></form><div class="mt-8 border-t border-white/10 pt-6 space-y-4 max-h-80 overflow-auto">@forelse($messages as $message)<div class="rounded-2xl p-4 {{ $message->sender_type==='candidate'?'bg-white/10 ml-8':'bg-orange-500/15 mr-8' }}"><div class="text-[10px] font-black uppercase tracking-widest text-white/45">{{ $message->sender_type==='candidate'?'Vous':'OROGNA' }} · {{ $message->created_at->format('d/m H:i') }}</div><p class="mt-2 whitespace-pre-line text-sm leading-6 text-white/85">{{ $message->body }}</p></div>@empty<p class="text-sm text-white/45">Votre conversation commencera ici.</p>@endforelse</div></div>
 </div></section>
@endsection
