@extends('layouts.admin')
@section('title','Page d’accueil — Administration')
@section('content')
<div class="mx-auto max-w-7xl p-5 lg:p-10">
  <div class="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div class="text-xs font-black uppercase tracking-[.2em] text-orange-500">Éditeur de contenu</div><h1 class="font-display mt-2 text-4xl font-extrabold">Piloter la page d’accueil</h1><p class="mt-2 max-w-3xl text-slate-500">Textes, photos et vidéo se modifient ici. Vous n’avez pas besoin de connaître le code.</p></div><a class="btn-primary" href="{{ route('home') }}" target="_blank">Voir le site ↗</a></div>
  <form method="POST" action="{{ route('admin.home.update') }}" enctype="multipart/form-data" class="mt-8 grid gap-6 lg:grid-cols-2">@csrf @method('PUT')
    <section class="admin-editor-card lg:col-span-2"><div class="admin-editor-heading"><span>00</span><div><h2>Sections visibles</h2><p>Activez ou masquez une section sans supprimer son contenu. Les réglages restent récupérables à tout moment.</p></div></div><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach(['marquee'=>'Bandeau des expertises','conviction'=>'Notre conviction','expertises'=>'Nos expertises','about'=>'À propos','impact'=>'Notre signature','careers'=>'Carrières','trainings'=>'Formations','cta'=>'Appel à l’action final'] as $key=>$label)<label class="flex cursor-pointer items-center justify-between rounded-2xl bg-slate-50 p-4"><span class="text-sm font-bold">{{ $label }}</span><input type="hidden" name="settings[section_{{ $key }}]" value="0"><input type="checkbox" name="settings[section_{{ $key }}]" value="1" class="h-5 w-5 rounded" @checked(($settings['section_'.$key]->value ?? '1') !== '0')></label>@endforeach</div></section>
    <section class="admin-editor-card lg:col-span-2"><div class="admin-editor-heading"><span>01</span><div><h2>Hero & identité visuelle</h2><p>La première impression de vos visiteurs.</p></div></div><div class="grid gap-5 md:grid-cols-2">
      <div><label>Petit titre</label><input class="field" name="settings[hero_badge]" value="{{ $settings['hero_badge']->value ?? '' }}"></div>
      <div><label>Titre principal <small>(séparer les deux lignes avec |)</small></label><input class="field" name="settings[hero_title]" value="{{ $settings['hero_title']->value ?? '' }}"></div>
      <div class="md:col-span-2"><label>Texte d’introduction</label><textarea class="field" rows="4" name="settings[hero_text]">{{ $settings['hero_text']->value ?? '' }}</textarea></div>
      <div><label>Bouton principal</label><input class="field" name="settings[hero_cta]" value="{{ $settings['hero_cta']->value ?? '' }}"></div><div><label>Bouton secondaire</label><input class="field" name="settings[hero_secondary]" value="{{ $settings['hero_secondary']->value ?? '' }}"></div>
      <div class="md:col-span-2 media-upload-box"><label>Photo principale de l’accueil</label><div class="media-upload-grid"><div><input type="file" name="hero_image" accept="image/jpeg,image/png,image/webp" class="field"><small>JPG, PNG ou WebP · 12 Mo max</small></div><img src="{{ asset($settings['hero_image']->value ?? 'images/team-orogna.jpg') }}" alt="Aperçu" class="media-thumb"></div></div>
    </div></section>
    <section class="admin-editor-card lg:col-span-2"><div class="admin-editor-heading"><span>02</span><div><h2>Vidéo de présentation</h2><p>Ajoutez une vidéo YouTube, Vimeo ou un fichier MP4.</p></div></div><div class="grid gap-5 md:grid-cols-2"><div class="md:col-span-2"><label>URL vidéo</label><input class="field" name="settings[hero_video_url]" value="{{ $settings['hero_video_url']->value ?? '' }}" placeholder="https://www.youtube.com/watch?v=... ou /videos/orogna.mp4"></div><div><label>Titre vidéo</label><input class="field" name="settings[hero_video_title]" value="{{ $settings['hero_video_title']->value ?? '' }}"></div><div><label>Texte vidéo</label><input class="field" name="settings[hero_video_text]" value="{{ $settings['hero_video_text']->value ?? '' }}"></div><div class="md:col-span-2 media-upload-box"><label>Image de couverture de la vidéo</label><div class="media-upload-grid"><div><input type="file" name="hero_video_poster_upload" accept="image/jpeg,image/png,image/webp" class="field"><small>Si aucune vidéo n’est renseignée, cette image devient le visuel de présentation.</small></div><img src="{{ asset($settings['hero_video_poster']->value ?? 'images/team-orogna.jpg') }}" alt="Aperçu vidéo" class="media-thumb"></div></div></div></section>
    <section class="admin-editor-card"><div class="admin-editor-heading"><span>03</span><div><h2>Notre conviction</h2><p>Le bloc éditorial qui pose votre positionnement.</p></div></div><div class="space-y-5"><div><label>Libellé</label><input class="field" name="settings[conviction_kicker]" value="{{ $settings['conviction_kicker']->value ?? '' }}"></div><div><label>Titre</label><textarea class="field" rows="3" name="settings[conviction_title]">{{ $settings['conviction_title']->value ?? '' }}</textarea></div><div><label>Texte</label><textarea class="field" rows="5" name="settings[conviction_text]">{{ $settings['conviction_text']->value ?? '' }}</textarea></div></div></section>
    <section class="admin-editor-card"><div class="admin-editor-heading"><span>04</span><div><h2>Section image & impact</h2><p>Un bloc visuel pour donner plus de profondeur à l’accueil.</p></div></div><div class="space-y-5"><div><label>Titre</label><textarea class="field" rows="2" name="settings[impact_title]">{{ $settings['impact_title']->value ?? '' }}</textarea></div><div><label>Texte</label><textarea class="field" rows="4" name="settings[impact_text]">{{ $settings['impact_text']->value ?? '' }}</textarea></div><div class="media-upload-box"><label>Image</label><div class="media-upload-grid"><div><input type="file" name="impact_image_upload" accept="image/jpeg,image/png,image/webp" class="field"><small>Photo d’équipe, bureau, formation ou terrain.</small></div><img src="{{ asset($settings['impact_image']->value ?? 'images/office.jpg') }}" alt="Aperçu" class="media-thumb"></div></div></div></section>
    <section class="admin-editor-card"><div class="admin-editor-heading"><span>05</span><div><h2>À propos</h2><p>Le bloc de présentation de l’entreprise.</p></div></div><div class="space-y-5"><div><label>Titre</label><textarea class="field" rows="3" name="settings[about_title]">{{ $settings['about_title']->value ?? '' }}</textarea></div><div><label>Points forts <small>(séparés par |)</small></label><input class="field" name="settings[about_points]" value="{{ $settings['about_points']->value ?? '' }}"></div><div class="media-upload-box"><label>Image À propos</label><div class="media-upload-grid"><div><input type="file" name="about_image_upload" accept="image/jpeg,image/png,image/webp" class="field"></div><img src="{{ asset($settings['about_image']->value ?? 'images/about.jpg') }}" alt="Aperçu" class="media-thumb"></div></div></div></section>
    <section class="admin-editor-card"><div class="admin-editor-heading"><span>06</span><div><h2>Appel à l’action final</h2><p>La dernière invitation avant le pied de page.</p></div></div><div class="space-y-5"><div><label>Libellé</label><input class="field" name="settings[cta_kicker]" value="{{ $settings['cta_kicker']->value ?? '' }}"></div><div><label>Titre</label><textarea class="field" rows="2" name="settings[cta_title]">{{ $settings['cta_title']->value ?? '' }}</textarea></div><div><label>Texte</label><textarea class="field" rows="4" name="settings[cta_text]">{{ $settings['cta_text']->value ?? '' }}</textarea></div><div class="media-upload-box"><label>Image de fond</label><div class="media-upload-grid"><div><input type="file" name="cta_image_upload" accept="image/jpeg,image/png,image/webp" class="field"></div><img src="{{ asset($settings['cta_image']->value ?? 'images/expertise.jpg') }}" alt="Aperçu" class="media-thumb"></div></div></div></section>
    <div class="lg:col-span-2 flex flex-col gap-4 rounded-3xl bg-[#103326] p-6 text-white sm:flex-row sm:items-center sm:justify-between"><div><strong class="font-display text-lg">Tout est prêt ?</strong><p class="mt-1 text-sm text-white/55">Enregistrez vos changements puis vérifiez le rendu sur le site.</p></div><button class="or-btn or-btn-orange">Enregistrer la page ↗</button></div>
  </form>
</div>
@endsection
