<?php $__env->startSection('title','Candidatures — Administration'); ?>
<?php $__env->startSection('content'); ?>
<div class="mx-auto max-w-7xl p-5 lg:p-10">
  <div class="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div class="text-xs font-black uppercase tracking-widest text-orange-500">Recrutement</div><h1 class="font-display mt-2 text-4xl font-extrabold">Candidatures</h1><p class="mt-2 text-slate-500">Recherchez, classez et suivez chaque candidat depuis son arrivée jusqu’à la décision finale.</p></div><div class="rounded-full bg-white px-4 py-2 text-sm font-black shadow-sm ring-1 ring-slate-100"><?php echo e($items->total()); ?> dossier(s)</div></div>
  <form class="mt-7 grid gap-3 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-100 md:grid-cols-[1fr_220px_auto]" method="GET"><input class="field" name="q" value="<?php echo e($q); ?>" placeholder="Rechercher un nom, email ou téléphone…"><select class="field" name="status"><option value="">Tous les statuts</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['nouvelle'=>'Nouvelle','en_etude'=>'En étude','entretien'=>'Entretien','retenue'=>'Retenue','rejetee'=>'Rejetée']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $k=>$v): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($k); ?>" <?php if($status===$k): echo 'selected'; endif; ?>><?php echo e($v); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select><button class="or-btn or-btn-orange">Filtrer</button></form>
  <div class="mt-6 space-y-4"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $a): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
    <article class="overflow-hidden rounded-[28px] bg-white shadow-sm ring-1 ring-slate-100"><div class="p-6 lg:p-7"><div class="flex flex-col justify-between gap-5 lg:flex-row"><div class="min-w-0"><div class="flex flex-wrap items-center gap-3"><h2 class="font-display text-xl font-extrabold"><?php echo e($a->candidate_name); ?></h2><span class="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-black uppercase"><?php echo e(str_replace('_',' ',$a->status)); ?></span></div><div class="mt-2 text-sm text-slate-400"><a href="mailto:<?php echo e($a->candidate_email); ?>" class="font-semibold hover:text-green-700"><?php echo e($a->candidate_email); ?></a> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($a->phone): ?> · <?php echo e($a->phone); ?> <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($a->city): ?> · <?php echo e($a->city); ?> <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><div class="mt-3 text-sm font-bold text-slate-700"><?php echo e($a->jobOffer?->title ?? 'Candidature spontanée'); ?></div><div class="mt-1 text-xs text-slate-400">Reçue le <?php echo e(optional($a->submitted_at)->format('d/m/Y à H:i')); ?></div></div>
      <div class="flex flex-wrap gap-2"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($a->cv_path): ?><a class="rounded-full bg-green-50 px-4 py-2 text-xs font-black text-green-700" href="<?php echo e(route('admin.applications.download',[$a,'cv'])); ?>">Télécharger CV</a><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($a->cover_letter_path): ?><a class="rounded-full bg-orange-50 px-4 py-2 text-xs font-black text-orange-700" href="<?php echo e(route('admin.applications.download',[$a,'letter'])); ?>">Lettre</a><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></div>
      <div class="mt-6 grid gap-5 lg:grid-cols-[260px_1fr]">
        <form method="POST" action="<?php echo e(route('admin.applications.status',$a)); ?>" class="rounded-2xl bg-slate-50 p-4"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><label class="mb-2 block text-xs font-black uppercase tracking-wider text-slate-400">Étape du dossier</label><select class="field" name="status"><option value="nouvelle" <?php if($a->status==='nouvelle'): echo 'selected'; endif; ?>>Nouvelle</option><option value="en_etude" <?php if($a->status==='en_etude'): echo 'selected'; endif; ?>>En étude</option><option value="entretien" <?php if($a->status==='entretien'): echo 'selected'; endif; ?>>Entretien</option><option value="retenue" <?php if($a->status==='retenue'): echo 'selected'; endif; ?>>Retenue</option><option value="rejetee" <?php if($a->status==='rejetee'): echo 'selected'; endif; ?>>Rejetée</option></select><label class="mt-4 mb-2 block text-xs font-black uppercase tracking-wider text-slate-400">Notes internes</label><textarea class="field" name="admin_notes" rows="4" placeholder="Ex. entretien le 18/09, profil à rappeler…"><?php echo e($a->admin_notes); ?></textarea><button class="mt-3 w-full rounded-full bg-[#103326] px-4 py-3 text-xs font-black text-white">Enregistrer le dossier</button></form>
        <div class="rounded-2xl border border-slate-100 p-5"><div class="text-xs font-black uppercase tracking-wider text-slate-400">Message du candidat</div><p class="mt-3 whitespace-pre-line text-sm leading-7 text-slate-600"><?php echo e($a->message ?: 'Aucun message joint à cette candidature.'); ?></p></div>
      </div>
    </div></article>
  <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?><div class="rounded-3xl bg-white p-16 text-center shadow-sm"><div class="text-4xl">◎</div><h2 class="mt-4 font-display text-xl font-extrabold">Aucune candidature trouvée</h2><p class="mt-2 text-sm text-slate-400">Essayez de modifier votre recherche ou vos filtres.</p></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div>
  <div class="mt-6"><?php echo e($items->links()); ?></div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\laragon\www\orogna-consulting-pro-v10-premium-2026-backoffice-pro\orogna-v10-work\resources\views/admin/applications/index.blade.php ENDPATH**/ ?>