<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\GalleryAlbum;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
class GalleryController extends Controller{
 public function index(){return view('admin.gallery.index',['albums'=>GalleryAlbum::orderBy('sort_order')->orderByDesc('created_at')->get()]);}
 public function store(Request $r){$d=$r->validate(['title'=>'required|string|max:180','slug'=>'nullable|string|max:180','description'=>'nullable|string|max:2000','cover_image'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:12288','images'=>'nullable|array','images.*'=>'image|mimes:jpg,jpeg,png,webp,gif|max:12288','sort_order'=>'nullable|integer|min:0|max:9999']);$slug=Str::slug($d['slug']??$d['title']);if(GalleryAlbum::where('slug',$slug)->exists())$slug.='-'.Str::lower(Str::random(5));$paths=$this->storeImages($r->file('images',[]));$cover=$this->storeOne($r->file('cover_image'));if(!$cover&&$paths)$cover=$paths[0];GalleryAlbum::create(['title'=>$d['title'],'slug'=>$slug,'description'=>$d['description']??null,'cover_image'=>$cover,'images'=>$paths,'is_published'=>$r->boolean('is_published',true),'sort_order'=>(int)($d['sort_order']??0)]);return back()->with('success','Album galerie créé.');}
 public function update(Request $r,GalleryAlbum $album){$d=$r->validate(['title'=>'required|string|max:180','description'=>'nullable|string|max:2000','cover_image'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:12288','images'=>'nullable|array','images.*'=>'image|mimes:jpg,jpeg,png,webp,gif|max:12288','sort_order'=>'nullable|integer|min:0|max:9999']);$images=$album->images?:[];if($new=$this->storeImages($r->file('images',[])))$images=array_values(array_merge($images,$new));$cover=$album->cover_image;if($r->hasFile('cover_image'))$cover=$this->storeOne($r->file('cover_image'));elseif(!$cover&&$images)$cover=$images[0];$album->update(['title'=>$d['title'],'description'=>$d['description']??null,'cover_image'=>$cover,'images'=>$images,'is_published'=>$r->boolean('is_published'),'sort_order'=>(int)($d['sort_order']??0)]);return back()->with('success','Album galerie mis à jour.');}
 public function deleteImage(Request $r,GalleryAlbum $album){$r->validate(['path'=>'required|string']);$path=$r->string('path')->toString();$images=array_values(array_filter($album->images?:[],fn($image)=>$image!==$path));$cover=$album->cover_image===$path?($images[0]??null):$album->cover_image;$this->removePublicFile($path);$album->update(['images'=>$images,'cover_image'=>$cover]);return back()->with('success','Image retirée de l’album.');}
 public function delete(GalleryAlbum $album){foreach(($album->images?:[]) as $image)$this->removePublicFile($image);if($album->cover_image&&!in_array($album->cover_image,$album->images?:[],true))$this->removePublicFile($album->cover_image);$album->delete();return back()->with('success','Album supprimé.');}
 private function storeImages(array $files):array{$paths=[];foreach($files as $file)if($file)$paths[]=$this->storeOne($file);return array_values(array_filter($paths));}
 private function storeOne($file):?string{if(!$file)return null;$dir=public_path('uploads/gallery');if(!is_dir($dir))mkdir($dir,0755,true);$name=Str::slug(pathinfo($file->getClientOriginalName(),PATHINFO_FILENAME)).'-'.Str::lower(Str::random(8)).'.'.$file->getClientOriginalExtension();$file->move($dir,$name);return 'uploads/gallery/'.$name;}
 private function removePublicFile(string $path):void{if(!str_starts_with($path,'uploads/gallery/'))return;$safe=ltrim(str_replace(['../','..\\'], '',$path),'/\\');$full=public_path($safe);$base=realpath(public_path('uploads/gallery'));$real=realpath($full);if($base&&$real&&is_file($full)&&str_starts_with($real,$base))@unlink($full);}
}
